config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "dapps#index"

  resources :dapps, only: [:index, :show]
  resources :banners, only: [:index, :show]
  # get 'info', to: 'dapps#info'
  get 'more/:type_name', to: 'dapps#more', as: "more_dapps"
  get 'dapps/type/:id', to: 'dapps#dapp_type', as: "dapps_type"
  get 'mine', to: 'dapps#mine'
  get 'history', to: 'dapps#history'

  namespace :admin do
    resources :images
    resources :banners
    resources :dapps
    resources :sessions, only: [:new, :create]
    get 'login', to: "sessions#new", as: :login
    match 'logout', to: "sessions#destroy", via: [:get, :delete], as: :logout
  end

end

app/models/banner.rb
class Banner < ApplicationRecord
  include VersionControlConcern

  validates :start_at, presence: true
  validates :end_at, presence: true

  validates :image_url, presence: true
end

app/controllers/admin/banners_controller.rb
class Admin::BannersController < Admin::ApplicationController
  before_action :set_banner, only: [:show, :edit, :update, :destroy]

  # GET /banners
  # GET /banners.json
  def index
    @banners = Banner.order(updated_at: :desc).page(params[:page])
  end

  # GET /banners/1
  # GET /banners/1.json
  def show
  end

  # GET /banners/new
  def new
    @banner = Banner.new
  end

  # GET /banners/1/edit
  def edit
  end

  # POST /banners
  # POST /banners.json
  def create
    @banner = Banner.new(banner_params)

    respond_to do |format|
      if @banner.save
        format.html { redirect_to admin_banner_path(@banner), notice: 'Banner was successfully created.' }
        format.json { render :show, status: :created, location: @banner }
      else
        format.html { render :new }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banners/1
  # PATCH/PUT /banners/1.json
  def update
    respond_to do |format|
      if @banner.update(banner_params)
        format.html { redirect_to admin_banner_path(@banner), notice: 'Banner was successfully updated.' }
        format.json { render :show, status: :ok, location: @banner }
      else
        format.html { render :edit }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banners/1
  # DELETE /banners/1.json
  def destroy
    @banner.destroy
    respond_to do |format|
      format.html { redirect_to admin_banners_url, notice: 'Banner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banner
      @banner = Banner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def banner_params
      params.require(:banner).permit(:image_url, :address, :start_at, :end_at, :ios_version, :android_version)
    end
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  def index
    now = Time.now
    options = {
      start_at_lteq: now,
      end_at_gteq: now,
      ios_version_number_lteq: handle_version(params[:ios_version]),
      android_version_number_lteq: handle_version(params[:android_version]),
    }

    @banners = Banner.ransack(options).result
  end

  def show
    @banner = Banner.find_by(id: params[:id])
  end

  private def handle_version(version)
    return if version.blank?
    Dapp.handle_version(version)
  end

end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/admin/banners/_form.html.erb
<div class="container mt-5">
  <%= form_with(model: [:admin, banner], scope: :banner, local: true) do |form| %>
    <% if banner.errors.any? %>
      <div id="error_explanation" class="alert alert-danger" role="alert">
        <h2><%= pluralize(banner.errors.count, "error") %> prohibited this banner from being saved:</h2>

        <ul>
          <% banner.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name, '图片' %>
      <%= form.text_field :image_url, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :photo, '链接' %>
      <%= form.text_field :address, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :start_at, '上架时间' %>
      <%= form.datetime_select :start_at, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :end_at, '下架时间' %>
      <%= form.datetime_select :end_at, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :ios_version, 'iOS 版本' %>
      <%= form.text_field :ios_version, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :android_version, 'Android 版本' %>
      <%= form.text_field :android_version, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.submit '提交', class: "btn btn-outline-primary float-right" %>
    </div>
  <% end %>
</div>

app/views/admin/banners/edit.html.erb
<% provide :title, "更新 Banner" %>
<% provide :back_url, admin_banners_path %>

<%= render 'form', banner: @banner %>

<div class="container">
  <%= link_to '显示详情', admin_banner_path(@banner) , class: "btn btn-outline-secondary" %>
</div>

app/views/admin/banners/index.html.erb
<% provide :title, 'Banners' %>

<div class="container mt-5">
  <% unless notice.blank? %>
    <div class="alert alert-info" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">图片</th>
        <th scope="col">链接</th>
        <th scope="col">上架时间</th>
        <th scope="col">下架时间</th>
        <th scope="col">iOS 版本</th>
        <th scope="col">Android 版本</th>
        <th scope="col" colspan="3"></th>
      </tr>
    </thead>

    <tbody>

      <% @banners.each do |banner| %>
        <tr>
          <td><%= handle_image_url banner.image_url %></td>
          <td><%= link_to_if_exist banner.address %></td>
          <td><%= banner.start_at %></td>
          <td><%= banner.end_at %></td>
          <td><%= banner.ios_version %></td>
          <td><%= banner.android_version %></td>
          <td>
            <a href="<%= admin_banner_path(banner) %>">
              <i class="fas fa-info-circle"></i>
            </a>
          </td>
          <td>
            <a href="<%= edit_admin_banner_path(banner) %>">
              <i class="far fa-edit"></i>
            </a>
          </td>
          <td>
            <%= link_to admin_banner_path(banner), method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>

  </table>

  <a href="<%= new_admin_banner_path %>" class="btn btn-primary bmd-btn-fab float-right center-button">
    <i class="fas fa-plus"></i>
  </a>

  <%= paginate @banners, views_prefix: "admin" %>

</div>

app/views/admin/banners/new.html.erb
<% provide :title, '新建 Banner' %>
<% provide :back_url, admin_banners_path %>

<%= render 'form', banner: @banner %>

app/views/admin/banners/show.html.erb
<% provide :title, "Banner 详情" %>
<% provide :back_url, admin_banners_path %>

<div class="container mt-5">
  <% unless notice.blank? %>
    <div class="alert alert-info" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <div class="row">
    <%= image_tag_if_exist(@banner.image_url) %>
  </div>

  <div class="row">
    <table class="table">
      <tbody>
        <tr>
          <td scope="col">图片</td>
          <td><%= link_to_if_exist @banner.image_url %></td>
        </tr>
        <tr>
          <td scope="col">链接</td>
          <td><%= link_to_if_exist @banner.address %></td>
        </tr>
        <tr>
          <td scope="col">上架时间</td>
          <td><%= @banner.start_at %></td>
        </tr>
        <tr>
          <td scope="col">下架时间</td>
          <td><%= @banner.end_at %></td>
        </tr>
        <tr>
          <td scope="col">iOS 版本</td>
          <td><%= @banner.ios_version %></td>
        </tr>
        <tr>
          <td scope="col">Android 版本</td>
          <td><%= @banner.android_version %></td>
        </tr>
      </tbody>
    </table>


  </div>

  <a href="<%= edit_admin_banner_path(@banner) %>" class="btn btn-secondary bmd-btn-fab float-right center-button">
    <i class="fas fa-edit"></i>
  </a>
</div>