config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "dapps#index"

  resources :dapps, only: [:index, :show]
  resources :banners, only: [:index, :show]
  # get 'info', to: 'dapps#info'
  get 'more/:type_name', to: 'dapps#more', as: "more_dapps"
  get 'dapps/type/:id', to: 'dapps#dapp_type', as: "dapps_type"
  get 'mine', to: 'dapps#mine'
  get 'history', to: 'dapps#history'

  namespace :admin do
    resources :images
    resources :banners
    resources :dapps
    resources :sessions, only: [:new, :create]
    get 'login', to: "sessions#new", as: :login
    match 'logout', to: "sessions#destroy", via: [:get, :delete], as: :logout
  end

end

app/models/dapp.rb
class Dapp < ApplicationRecord
  include VersionControlConcern

  translates :name, :intro, :desc
  globalize_accessors

  validates :start_at, presence: true
  validates :end_at, presence: true

  belongs_to :dapp_type

  scope :default_order, -> { order(updated_at: :desc) }

  enum d_type: {
    new_dapp: 10,
    popular: 20,
    exchange: 30,
  }

  def name_or_default
    name.blank? ? name_zh_cn : name
  end

  def intro_or_default
    intro.blank? ? intro_zh_cn : intro
  end

  def desc_or_default
    desc.blank? ? desc_zh_cn : desc
  end

end

app/models/dapp_type.rb
class DappType < ApplicationRecord
  has_many :dapps
  validates :name, presence: true, uniqueness: true

  translates :name
  globalize_accessors

  scope :default_order, -> { order(id: :asc) }

  def name_or_default
    name.blank? ? name_zh_cn : name
  end
end

app/controllers/admin/dapps_controller.rb
class Admin::DappsController < Admin::ApplicationController
  before_action :set_dapp, only: [:show, :edit, :update, :destroy]

  # GET /dapps
  # GET /dapps.json
  def index
    @dapps = Dapp.includes(:dapp_type).order(updated_at: :desc).page(params[:page])
  end

  # GET /dapps/1
  # GET /dapps/1.json
  def show
  end

  # GET /dapps/new
  def new
    @dapp = Dapp.new
  end

  # GET /dapps/1/edit
  def edit
  end

  # POST /dapps
  # POST /dapps.json
  def create
    @dapp = Dapp.new(dapp_params)

    respond_to do |format|
      if @dapp.save
        format.html { redirect_to admin_dapp_path(@dapp), notice: 'Dapp was successfully created.' }
        format.json { render :show, status: :created, location: @dapp }
      else
        format.html { render :new }
        format.json { render json: @dapp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dapps/1
  # PATCH/PUT /dapps/1.json
  def update
    respond_to do |format|
      if @dapp.update(dapp_params)
        format.html { redirect_to admin_dapp_path(@dapp), notice: 'Dapp was successfully updated.' }
        format.json { render :show, status: :ok, location: @dapp }
      else
        format.html { render :edit }
        format.json { render json: @dapp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dapps/1
  # DELETE /dapps/1.json
  def destroy
    @dapp.destroy
    respond_to do |format|
      format.html { redirect_to admin_dapps_url, notice: 'Dapp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_dapp
    @dapp = Dapp.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dapp_params
    params.require(:dapp).permit(:android_version, :developer, :end_at, :ios_version, :logo_url, :marketing_url, :publish_at, :score, :start_at, :url_address, :dapp_type_id, :filter_ip, *Dapp.globalize_attribute_names)
  end
end

app/controllers/dapps_controller.rb
class DappsController < ApplicationController

  def index
    options = get_options

    @banners = Banner.ransack(options).result
    # @dapps = Dapp.all.group_by { |dapp| dapp.d_type }
    @dapps = DappType.default_order.map do |dapp_type|
      { {id: dapp_type.id, name: dapp_type.name, name_zh_cn: dapp_type.name_zh_cn} => dapp_type.dapps.default_order.ransack(options).result.limit(3)&.map {|d| d.as_json.merge(name_zh_cn: d.name_zh_cn, desc_zh_cn: d.desc_zh_cn, intro_zh_cn: d.intro_zh_cn)} }
    end.reduce({}, :merge).reject {|k, v| v.empty?}
  end

  # GET /dapps/:id
  def show
    @dapp = Dapp.find_by(id: params[:id])
    @start_at = @dapp.start_at.to_s.split(' ')[0]
    @star = @dapp.score
    if @star < 0
      @star = 0
    elsif @star > 5
      @star = 5
    end
    @stargray = 5 - @star
  end

  # GET /dapp/more/:type_name
  def more
    options = get_options

    @dapp_type = DappType.find_by id: params[:type_name]
    @dapps = @dapp_type.dapps.default_order.ransack(options).result
  end

  # GET /dapp/type/:id
  def dapp_type
    @dapp_type = DappType.find_by id: params[:id]
    render json: { name: @dapp_type.name }
  end

  def mine
  end

  def history
  end

  private

  def handle_version(version)
    return if version.blank?
    Dapp.handle_version(version)
  end

  def get_options
    now = Time.now
    opt = {
      start_at_lteq: now,
      end_at_gteq: now,
      ios_version_number_lteq: handle_version(params[:ios_version]),
      android_version_number_lteq: handle_version(params[:android_version]),
    }

    if FilterIpUtils.china_mainland?(request.remote_ip)
      opt.merge!(filter_ip_eq: false)
    end

    opt
  end

end

app/helpers/admin/dapps_helper.rb
module Admin::DappsHelper
end

app/helpers/dapps_helper.rb
module DappsHelper
  def tag_to_text(tag)
    case tag
    when "new_dapp"
      "AppChain 应用"
    when "popular"
      "热门应用"
    else
      tag.to_s
    end
  end
end

app/views/admin/dapps/_form.html.erb
<div class="container mt-5">
  <%= form_with(model: [:admin, dapp], scope: :dapp, local: true) do |form| %>
    <% if dapp.errors.any? %>
      <div id="error_explanation" class="alert alert-danger" role="alert">
        <h2><%= pluralize(dapp.errors.count, "error") %> prohibited this dapp from being saved:</h2>

        <ul>
          <% dapp.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <% I18n.available_locales.each do |lang| %>
      <div class="form-group">
        <%= form.label :"#{transfer_i18n(:name, lang)}", "名称 #{lang}", class: "text-secondary" %>
        <%= form.text_field transfer_i18n(:name, lang), class: "form-control" %>
      </div>
    <% end %>

    <% I18n.available_locales.each do |lang| %>
      <div class="form-group">
        <%= form.label transfer_i18n(:desc, lang), "一句话描述 #{lang}", class: "text-secondary" %>
        <%= form.text_area transfer_i18n(:desc, lang), class: "form-control" %>
      </div>
    <% end %>

    <% I18n.available_locales.each do |lang| %>
      <div class="form-group">
        <%= form.label transfer_i18n(:intro, lang), "简介 #{lang}", class: "text-secondary" %>
        <%= form.text_area transfer_i18n(:intro, lang), class: "form-control" %>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :dapp_type_id, '类型', class: "text-secondary" %>
      <%= form.select :dapp_type_id, options_from_collection_for_select(DappType.default_order, "id", "name", dapp.dapp_type_id), {}, { class: "form-control" } %>
    </div>

    <div class="form-group">
      <%= form.label :score, '分数', class: "text-secondary" %>
      <%= form.number_field :score, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :developer, '开发者', class: "text-secondary" %>
      <%= form.text_field :developer, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :intro, 'IP筛选', class: "text-secondary" %>
      <%= form.select :filter_ip, options_for_select([true, false], dapp.filter_ip), {}, { class: "form-control" } %>
    </div>

    <div class="form-group">
      <%= form.label :ios_version, 'iOS 版本', class: "text-secondary" %>
      <%= form.text_field :ios_version, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :android_version, 'Android 版本', class: "text-secondary" %>
      <%= form.text_field :android_version, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :start_at, '上架时间', class: "text-secondary" %>
      <%= form.datetime_select :start_at, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :end_at, '下架时间', class: "text-secondary" %>
      <%= form.datetime_select :end_at, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :publish_at, '发布时间', class: "text-secondary" %>
      <%= form.datetime_select :publish_at, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :logo_url, 'icon url', class: "text-secondary" %>
      <%= form.text_field :logo_url, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :marketing_url, 'Marketing URL', class: "text-secondary" %>
      <%= form.text_field :marketing_url, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :url_address, 'DApp 地址', class: "text-secondary" %>
      <%= form.text_field :url_address, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.submit '提交', class: "btn btn-outline-primary float-right" %>
    </div>
  <% end %>
</div>

app/views/admin/dapps/_translation.html.erb
<% attrs.each do |attr, name| %>
  <% I18n.available_locales.each do |lang| %>
    <tr>
      <td scope="col"><%= name %> <br> <%= lang %></td>
      <td><%= dapp.send(transfer_i18n(attr, lang)) %></td>
    </tr>
  <% end %>
<% end %>

app/views/admin/dapps/edit.html.erb
<% provide :title, "编辑 Banner" %>
<% provide :back_url, admin_dapps_path %>

<%= render 'form', dapp: @dapp %>

<div class="container">
  <%= link_to '显示详情', admin_dapp_path(@dapp) , class: "btn btn-outline-secondary" %>
</div>

app/views/admin/dapps/index.html.erb
<% provide :title, 'DApps' %>

<div class="container mt-5">
  <% unless notice.blank? %>
    <div class="alert alert-info" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">名称</th>
        <th scope="col">一句话描述</th>
        <th scope="col">简介</th>
        <th scope="col">类型</th>
        <th scope="col">分数</th>
        <th scope="col">开发者</th>
        <th scope="col">IP筛选</th>
        <th scope="col">iOS version</th>
        <th scope="col">Android version</th>
        <th scope="col">上架时间</th>
        <th scope="col">下架时间</th>
        <th scope="col">发布时间</th>
        <th scope="col">icon</th>
        <th scope="col">Marketing</th>
        <th scope="col">DApp 地址</th>
        <th scope="col" colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @dapps.each do |dapp| %>
        <tr>
          <td><%= dapp.id %></td>
          <td><%= dapp.name %></td>
          <td><%= dapp.desc %></td>
          <td><%= dapp.intro %></td>
          <td><%= dapp.dapp_type&.name %></td>
          <td><%= dapp.score %></td>
          <td><%= dapp.developer %></td>
          <td><%= dapp.filter_ip %></td>
          <td><%= dapp.ios_version %></td>
          <td><%= dapp.android_version %></td>
          <td><%= dapp.start_at %></td>
          <td><%= dapp.end_at %></td>
          <td><%= dapp.publish_at %></td>
          <td><%= handle_image_url dapp.logo_url %></td>
          <td><%= handle_image_url dapp.marketing_url %></td>
          <td><%= link_to_if_exist(dapp.url_address) %></td>
          <td>
            <a href="<%= admin_dapp_path(dapp) %>">
              <i class="fas fa-info-circle"></i>
            </a>
          </td>
          <td>
            <a href="<%= edit_admin_dapp_path(dapp) %>">
              <i class="far fa-edit"></i>
            </a>
          </td>
          <td>
            <%= link_to admin_dapp_path(dapp), method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>

  </table>

  <a href="<%= new_admin_dapp_path %>" class="btn btn-primary bmd-btn-fab float-right center-button">
    <i class="fas fa-plus"></i>
  </a>

  <%= paginate @dapps, views_prefix: "admin" %>

</div>

app/views/admin/dapps/new.html.erb
<% provide :title, '新建 DApp' %>
<% provide :back_url, admin_dapps_path %>

<%= render 'form', dapp: @dapp %>

app/views/admin/dapps/show.html.erb
<% provide :title, "DApp 详情" %>
<% provide :back_url, admin_dapps_path %>

<div class="container mt-5">
  <% unless notice.blank? %>
    <div class="alert alert-info" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <div class="row">
    <table class="table">
      <tbody>
        <%= render "translation", dapp: @dapp, attrs: { name: "名称", desc: "一句话描述", intro: "简介" } %>

        <tr>
          <td scope="col">ID</td>
          <td><%= @dapp.id %></td>
        </tr>
        <tr>
          <td scope="col">类型</td>
          <td><%= @dapp.dapp_type&.name %></td>
        </tr>
        <tr>
          <td scope="col">分数</td>
          <td><%= @dapp.score %></td>
        </tr>
        <tr>
          <td scope="col">开发者</td>
          <td><%= @dapp.developer %></td>
        </tr>
        <tr>
          <td scope="col">IP筛选</td>
          <td><%= @dapp.filter_ip %></td>
        </tr>
        <tr>
          <td scope="col">iOS version</td>
          <td><%= @dapp.ios_version %></td>
        </tr>
        <tr>
          <td scope="col">Android version</td>
          <td><%= @dapp.android_version %></td>
        </tr>
        <tr>
          <td scope="col">上架时间</td>
          <td><%= @dapp.start_at %></td>
        </tr>
        <tr>
          <td scope="col">下架时间</td>
          <td><%= @dapp.end_at %></td>
        </tr>
        <tr>
          <td scope="col">发布时间</td>
          <td><%= @dapp.publish_at %></td>
        </tr>
        <tr>
          <td scope="col">icon</td>
          <td><%= handle_image_url @dapp.logo_url %></td>
        </tr>
        <tr>
          <td scope="col">icon url</td>
          <td><%= link_to_if_exist(@dapp.logo_url) %></td>
        </tr>
        <tr>
          <td scope="col">Marketing</td>
          <td><%= handle_image_url @dapp.marketing_url %></td>
        </tr>
        <tr>
          <td scope="col">Marketing url</td>
          <td><%= link_to_if_exist(@dapp.marketing_url) %></td>
        </tr>
        <tr>
          <td scope="col">DApp 地址</td>
          <td><%= link_to_if_exist(@dapp.url_address) %></td>
        </tr>
      </tbody>
    </table>


  </div>

  <a href="<%= edit_admin_dapp_path(@dapp) %>" class="btn btn-secondary bmd-btn-fab float-right center-button">
    <i class="fas fa-edit"></i>
  </a>
</div>