config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "dapps#index"

  resources :dapps, only: [:index, :show]
  resources :banners, only: [:index, :show]
  # get 'info', to: 'dapps#info'
  get 'more/:type_name', to: 'dapps#more', as: "more_dapps"
  get 'dapps/type/:id', to: 'dapps#dapp_type', as: "dapps_type"
  get 'mine', to: 'dapps#mine'
  get 'history', to: 'dapps#history'

  namespace :admin do
    resources :images
    resources :banners
    resources :dapps
    resources :sessions, only: [:new, :create]
    get 'login', to: "sessions#new", as: :login
    match 'logout', to: "sessions#destroy", via: [:get, :delete], as: :logout
  end

end

app/models/image.rb
class Image < ApplicationRecord
  has_one_attached :photo
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.order(updated_at: :desc).page(params[:page])
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to admin_image_path(@image), notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to admin_image_path(@image), notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to admin_images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:name, :photo)
    end
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
  def photo_path(image)
    rails_blob_path(image.photo)
  rescue
    ""
  end

  def photo_url(image)
    rails_blob_url(image.photo)
  rescue
    ""
  end

  def real_url(image)
    if (Rails.env.development? && ENV['QINIU_CLOUD'] == 'true') || Rails.env.production?
      cdn_url(image)
    else
      photo_url(image)
    end
  end

  private

  def cdn_url(image)
    protocol = ENV['QINIU_PROTOCOL']
    domain = ENV['QINIU_DOMAIN']
    key = image.photo&.key
    return "" if key.nil?
    "#{protocol}://#{domain}/#{key}"
  end
end

app/views/admin/images/_form.html.erb
<div class="container mt-5">
  <%= form_with(model: [:admin, image], scope: :image, local: true) do |form| %>
    <% if image.errors.any? %>
      <div id="error_explanation" class="alert alert-danger" role="alert">
        <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

        <ul>
          <% image.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name, '名称' %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :photo, '图片' %>
      <%= form.file_field :photo, class: "form-control-file" %>
    </div>

    <div class="actions">
      <%= form.submit '提交', class: "btn btn-outline-primary float-right" %>
    </div>
  <% end %>
</div>

app/views/admin/images/edit.html.erb
<% provide :title, "更新图片" %>
<% provide :back_url, admin_images_path %>

<%= render 'form', image: @image %>

<div class="container">
  <%= link_to '显示详情', admin_image_path(@image), class: "btn btn-outline-secondary" %>
</div>

app/views/admin/images/index.html.erb
<% provide :title, '图片列表' %>

<div class="container mt-5">
  <% unless notice.blank? %>
    <div class="alert alert-info" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">名称</th>
        <th scope="col">图片</th>
        <th scope="col">URL</th>
        <th scope="col" colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @images.each_with_index do |image, index| %>
        <tr>
          <td><%= image.name %></td>
          <td><%= handle_image_url photo_path(image) %></td>
          <td><%= link_to_if_exist real_url(image), id: "foo-#{index}" %></td>
          <td><i class="far fa-copy clipboard-btn" data-clipboard-target="<%= "#foo-#{index}" %>" style="cursor: pointer;"></i></td>
          <td>
            <a href="<%= admin_image_path(image) %>">
              <i class="fas fa-info-circle"></i>
            </a>
          </td>
          <td>
            <a href="<%= edit_admin_image_path(image) %>">
              <i class="far fa-edit"></i>
            </a>
          </td>
          <td>
            <%= link_to admin_image_path(image, action: :destroy), method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>

  </table>

  <a href="<%= new_admin_image_path %>" class="btn btn-primary bmd-btn-fab float-right center-button">
    <i class="fas fa-plus"></i>
  </a>

  <%= paginate @images, views_prefix: "admin" %>

</div>

app/views/admin/images/new.html.erb
<% provide :title, '新建图片' %>
<% provide :back_url, admin_images_path %>

<%= render 'form', image: @image %>

app/views/admin/images/show.html.erb
<% provide :title, "图片详情" %>
<% provide :back_url, admin_images_path %>

<div class="container mt-5">
  <% unless notice.blank? %>
    <div class="alert alert-info" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <div class="row">
    <%= image_tag_if_exist photo_path(@image) %>
  </div>

  <div class="row">
    <table class="table">
      <tbody>
        <tr>
          <td scope="col">名称</td>
          <td><%= @image.name %></td>
        </tr>
        <tr>
          <td scope="col">URL</td>
          <td><%= link_to_if_exist(real_url(@image), id: "foo") %></td>
          <td><i class="far fa-copy clipboard-btn" data-clipboard-target="#foo" style="cursor: pointer;"></i></td>
        </tr>
      </tbody>
    </table>
  </div>

  <a href="<%= edit_admin_image_path(@image) %>" class="btn btn-secondary bmd-btn-fab float-right center-button">
    <i class="fas fa-edit"></i>
  </a>

</div>