config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "dapps#index"

  resources :dapps, only: [:index, :show]
  resources :banners, only: [:index, :show]
  # get 'info', to: 'dapps#info'
  get 'more/:type_name', to: 'dapps#more', as: "more_dapps"
  get 'dapps/type/:id', to: 'dapps#dapp_type', as: "dapps_type"
  get 'mine', to: 'dapps#mine'
  get 'history', to: 'dapps#history'

  namespace :admin do
    resources :images
    resources :banners
    resources :dapps
    resources :sessions, only: [:new, :create]
    get 'login', to: "sessions#new", as: :login
    match 'logout', to: "sessions#destroy", via: [:get, :delete], as: :logout
  end

end

app/views/layouts/_admin_header.html.erb
<!--<header class="header-box">-->

<!--  <div class="header-limiter">-->
<!--    <nav>-->
<!--      <a href="<%#= admin_images_path %>">Images</a>-->
<!--      <a href="<%#= admin_banners_path %>">Banners</a>-->
<!--      <a href="<%#= admin_dapps_path %>">Dapps</a>-->

<%# if logged_in? %>
<!--        <a href="<%#= admin_logout_path %>">退出登录</a>-->
<%# else %>
<!--        <a href="<%#= admin_login_path %>">登录</a>-->
<%# end %>
<!--    </nav>-->
<!--  </div>-->

<!--</header>-->

<nav class="navbar navbar-expand-lg navbar-light justify-content-between bg-primary">
  <span class="navbar-brand text-light"><%= yield(:title) %></span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="text-light nav-item nav-link <%= 'active' if params[:controller] == "admin/images" %>" href="<%= admin_images_path %>">Images
        <span class="sr-only">(current)</span>
      </a>
      <a class="text-light nav-item nav-link <%= 'active' if params[:controller] == "admin/banners" %>" href="<%= admin_banners_path %>">Banners</a>
      <a class="text-light nav-item nav-link <%= 'active' if params[:controller] == "admin/dapps" %>" href="<%= admin_dapps_path %>">Dapps</a>

      <% if logged_in? %>
        <a class="text-light nav-item nav-link" href="<%= admin_logout_path %>">退出登录</a>
      <% else %>
        <a class="text-light nav-item nav-link" href="<%= admin_login_path %>">登录</a>
      <% end %>
    </div>

  </div>
  <div>
    <a href="<%= yield(:back_url).blank? ? "javascript:history.back()" : yield(:back_url) %>">
      <i class="fas fa-arrow-left text-light"></i>
    </a>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dapp Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'admin' %>
    <%= stylesheet_pack_tag 'admin', media: 'all' %>
  </head>

  <body>
    <%= render "layouts/admin_header" unless params[:controller] == "admin/sessions" %>

    <%= yield %>

    <%# console if Rails.env.development? %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title || "Dapps" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="environment" content='<%= Rails.env %>'>
    <meta name="locale" content='<%= I18n.locale %>'>
    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>